# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueManagerTeamEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueManagerTeamEdit(object):
    def setupUi(self, LeagueManagerTeamEdit):
        LeagueManagerTeamEdit.setObjectName("LeagueManagerTeamEdit")
        LeagueManagerTeamEdit.resize(1070, 653)
        self.centralwidget = QtWidgets.QWidget(LeagueManagerTeamEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(900, 40, 90, 28))
        self.SaveButton.setToolTipDuration(3)
        self.SaveButton.setWhatsThis("")
        self.SaveButton.setAutoFillBackground(False)
        self.SaveButton.setStyleSheet("background-color:rgb(66, 255, 33);")
        self.SaveButton.setObjectName("SaveButton")
        self.TeamEdit = QtWidgets.QLabel(self.centralwidget)
        self.TeamEdit.setGeometry(QtCore.QRect(60, 0, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.TeamEdit.setFont(font)
        self.TeamEdit.setStyleSheet("")
        self.TeamEdit.setScaledContents(True)
        self.TeamEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.TeamEdit.setObjectName("TeamEdit")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(60, 40, 90, 28))
        self.BackButton.setStyleSheet("background-color:rgb(255, 0, 4);")
        self.BackButton.setObjectName("BackButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(61, 80, 951, 531))
        self.tableWidget.setMinimumSize(QtCore.QSize(951, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(700, 40, 161, 28))
        self.AddButton.setStyleSheet("background-color:rgb(41, 109, 255);")
        self.AddButton.setObjectName("AddButton")
        LeagueManagerTeamEdit.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LeagueManagerTeamEdit)
        self.statusbar.setObjectName("statusbar")
        LeagueManagerTeamEdit.setStatusBar(self.statusbar)

        self.retranslateUi(LeagueManagerTeamEdit)
        QtCore.QMetaObject.connectSlotsByName(LeagueManagerTeamEdit)

    def retranslateUi(self, LeagueManagerTeamEdit):
        _translate = QtCore.QCoreApplication.translate
        LeagueManagerTeamEdit.setWindowTitle(_translate("LeagueManagerTeamEdit", "League Manager: Team Edit"))
        self.SaveButton.setToolTip(_translate("LeagueManagerTeamEdit", "Saves the current league view to the database."))
        self.SaveButton.setText(_translate("LeagueManagerTeamEdit", "Save"))
        self.TeamEdit.setText(_translate("LeagueManagerTeamEdit", "Team Edit"))
        self.BackButton.setText(_translate("LeagueManagerTeamEdit", "Back"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LeagueManagerTeamEdit", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LeagueManagerTeamEdit", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("LeagueManagerTeamEdit", "Actions"))
        self.AddButton.setText(_translate("LeagueManagerTeamEdit", "Add New Member"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueManagerTeamEdit = QtWidgets.QMainWindow()
    ui = Ui_LeagueManagerTeamEdit()
    ui.setupUi(LeagueManagerTeamEdit)
    LeagueManagerTeamEdit.show()
    sys.exit(app.exec_())
