# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueManager(object):
    def setupUi(self, LeagueManager):
        LeagueManager.setObjectName("LeagueManager")
        LeagueManager.resize(1068, 657)
        self.centralwidget = QtWidgets.QWidget(LeagueManager)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 90, 951, 531))
        self.tableWidget.setMinimumSize(QtCore.QSize(951, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.CurrentLeaguesLabel = QtWidgets.QLabel(self.centralwidget)
        self.CurrentLeaguesLabel.setGeometry(QtCore.QRect(50, 50, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.CurrentLeaguesLabel.setFont(font)
        self.CurrentLeaguesLabel.setStyleSheet("")
        self.CurrentLeaguesLabel.setScaledContents(True)
        self.CurrentLeaguesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentLeaguesLabel.setObjectName("CurrentLeaguesLabel")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(910, 60, 90, 28))
        self.SaveButton.setAutoFillBackground(False)
        self.SaveButton.setStyleSheet("background-color:rgb(66, 255, 33);")
        self.SaveButton.setObjectName("SaveButton")
        self.LoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(799, 60, 111, 28))
        self.LoadButton.setObjectName("LoadButton")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(689, 60, 111, 28))
        self.AddButton.setObjectName("AddButton")
        LeagueManager.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(LeagueManager)
        self.statusBar.setObjectName("statusBar")
        LeagueManager.setStatusBar(self.statusBar)

        self.retranslateUi(LeagueManager)
        QtCore.QMetaObject.connectSlotsByName(LeagueManager)

    def retranslateUi(self, LeagueManager):
        _translate = QtCore.QCoreApplication.translate
        LeagueManager.setWindowTitle(_translate("LeagueManager", "League Manager"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LeagueManager", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LeagueManager", "Teams"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("LeagueManager", "Actions"))
        self.CurrentLeaguesLabel.setText(_translate("LeagueManager", "Current Leagues"))
        self.SaveButton.setWhatsThis(_translate("LeagueManager", "Saves the current league view to the database."))
        self.SaveButton.setText(_translate("LeagueManager", "Save"))
        self.LoadButton.setText(_translate("LeagueManager", "Load Database"))
        self.AddButton.setText(_translate("LeagueManager", "Add New League"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueManager = QtWidgets.QMainWindow()
    ui = Ui_LeagueManager()
    ui.setupUi(LeagueManager)
    LeagueManager.show()
    sys.exit(app.exec_())
