# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueManagerLeagueEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueManagerLeagueEdit(object):
    def setupUi(self, LeagueManagerLeagueEdit):
        LeagueManagerLeagueEdit.setObjectName("LeagueManagerLeagueEdit")
        LeagueManagerLeagueEdit.resize(1070, 655)
        self.centralwidget = QtWidgets.QWidget(LeagueManagerLeagueEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 100, 951, 531))
        self.tableWidget.setMinimumSize(QtCore.QSize(951, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(300)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.LoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(760, 60, 111, 28))
        self.LoadButton.setStyleSheet("background-color:rgb(201, 5, 255);")
        self.LoadButton.setObjectName("LoadButton")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(600, 60, 141, 28))
        self.AddButton.setStyleSheet("background-color:rgb(41, 109, 255);")
        self.AddButton.setObjectName("AddButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(900, 60, 90, 28))
        self.SaveButton.setAutoFillBackground(False)
        self.SaveButton.setStyleSheet("background-color:rgb(66, 255, 33);")
        self.SaveButton.setObjectName("SaveButton")
        self.LeagueEdit = QtWidgets.QLabel(self.centralwidget)
        self.LeagueEdit.setGeometry(QtCore.QRect(60, 0, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.LeagueEdit.setFont(font)
        self.LeagueEdit.setStyleSheet("")
        self.LeagueEdit.setScaledContents(True)
        self.LeagueEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LeagueEdit.setObjectName("LeagueEdit")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(60, 60, 90, 28))
        self.BackButton.setStyleSheet("background-color:rgb(255, 0, 4);")
        self.BackButton.setObjectName("BackButton")
        LeagueManagerLeagueEdit.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LeagueManagerLeagueEdit)
        self.statusbar.setObjectName("statusbar")
        LeagueManagerLeagueEdit.setStatusBar(self.statusbar)

        self.retranslateUi(LeagueManagerLeagueEdit)
        QtCore.QMetaObject.connectSlotsByName(LeagueManagerLeagueEdit)

    def retranslateUi(self, LeagueManagerLeagueEdit):
        _translate = QtCore.QCoreApplication.translate
        LeagueManagerLeagueEdit.setWindowTitle(_translate("LeagueManagerLeagueEdit", "League Manager: League Edit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LeagueManagerLeagueEdit", "Team Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("LeagueManagerLeagueEdit", "Members"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("LeagueManagerLeagueEdit", "Actions"))
        self.LoadButton.setText(_translate("LeagueManagerLeagueEdit", "Load File"))
        self.AddButton.setText(_translate("LeagueManagerLeagueEdit", "Add New Team"))
        self.SaveButton.setWhatsThis(_translate("LeagueManagerLeagueEdit", "Saves the current league view to the database."))
        self.SaveButton.setText(_translate("LeagueManagerLeagueEdit", "Save"))
        self.LeagueEdit.setText(_translate("LeagueManagerLeagueEdit", "League Edit"))
        self.BackButton.setText(_translate("LeagueManagerLeagueEdit", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueManagerLeagueEdit = QtWidgets.QMainWindow()
    ui = Ui_LeagueManagerLeagueEdit()
    ui.setupUi(LeagueManagerLeagueEdit)
    LeagueManagerLeagueEdit.show()
    sys.exit(app.exec_())
