# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeagueManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LeagueManager(object):
    def setupUi(self, LeagueManager):
        LeagueManager.setObjectName("LeagueManager")
        LeagueManager.resize(1068, 657)
        self.centralwidget = QtWidgets.QWidget(LeagueManager)
        self.centralwidget.setObjectName("centralwidget")
        self.CurrentLeaguesLabel = QtWidgets.QLabel(self.centralwidget)
        self.CurrentLeaguesLabel.setGeometry(QtCore.QRect(60, 0, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.CurrentLeaguesLabel.setFont(font)
        self.CurrentLeaguesLabel.setStyleSheet("")
        self.CurrentLeaguesLabel.setScaledContents(True)
        self.CurrentLeaguesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentLeaguesLabel.setObjectName("CurrentLeaguesLabel")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(900, 50, 90, 28))
        self.SaveButton.setAutoFillBackground(False)
        self.SaveButton.setStyleSheet("background-color:rgb(66, 255, 33);")
        self.SaveButton.setObjectName("SaveButton")
        self.LoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(770, 50, 111, 28))
        self.LoadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoadButton.setStyleSheet("background-color:rgb(201, 5, 255);")
        self.LoadButton.setObjectName("LoadButton")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(600, 50, 151, 28))
        self.AddButton.setStyleSheet("background-color:rgb(41, 109, 255);")
        self.AddButton.setObjectName("AddButton")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(70, 90, 931, 531))
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.tableView.setVerticalHeader(0, "Name")
        self.tableView.setVerticalHeader(1, "Teams")
        self.tableView.setVerticalHeader(2, "Actions")
        LeagueManager.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(LeagueManager)
        self.statusBar.setObjectName("statusBar")
        LeagueManager.setStatusBar(self.statusBar)

        self.retranslateUi(LeagueManager)
        QtCore.QMetaObject.connectSlotsByName(LeagueManager)

    def retranslateUi(self, LeagueManager):
        _translate = QtCore.QCoreApplication.translate
        LeagueManager.setWindowTitle(_translate("LeagueManager", "League Manager"))
        self.CurrentLeaguesLabel.setText(_translate("LeagueManager", "Current Leagues"))
        self.SaveButton.setWhatsThis(_translate("LeagueManager", "Saves the current league view to the database."))
        self.SaveButton.setText(_translate("LeagueManager", "Save"))
        self.LoadButton.setText(_translate("LeagueManager", "Load Database"))
        self.AddButton.setText(_translate("LeagueManager", "Add New League"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LeagueManager = QtWidgets.QMainWindow()
    ui = Ui_LeagueManager()
    ui.setupUi(LeagueManager)
    LeagueManager.show()
    sys.exit(app.exec_())
